# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='plateforme',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Plateforme'),
        ),
    ]
