# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lien',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
