# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20161014_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='plateforme',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
