# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_plateforme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='base',
            name='url',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='plateforme',
            name='libelle',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
