# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20161014_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='plateforme',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
