# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20161014_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plateforme',
            new_name='Editeur',
        ),
        migrations.AlterModelTable(
            name='editeur',
            table='editeurs',
        ),
    ]
