# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20161014_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='plateforme',
            new_name='editeur',
        ),
    ]
